#!/bin/bash

###########################################################################

SERVER=${1}
SOURCE=${2}

if [ -z "${SERVER}" ] || [ -z "${SOURCE}" ] ; then
cat<<EOF
Usage: file-sync [server] [source]
       server: IP or IP:PORT
       source: file name

EOF
exit 1
fi

###########################################################################

TMDIR=/tmp/file-sync
DLDIR=/var/cache/file-sync

###########################################################################

[ -d ${TMDIR} ] || mkdir -p ${TMDIR}
[ -d ${DLDIR} ] || mkdir -p ${DLDIR}

###########################################################################

# Lecture ETag local (cache)
ETag=$(grep "^ETag:" ${TMDIR}/${SOURCE}.headers 2>/dev/null |cut -d'"' -f2)

# Hôte distant joignable ?
ping -t5 -c1 ${SERVER%:*} 2>/dev/null >/dev/null
if [ $? -ne 0 ] ; then
	echo "host '${SERVER}' is unreachable" |logger -t "file-sync"
	exit 2
fi

# Lecture ETag distant
curl -m2 -sS -D ${TMDIR}/${SOURCE}.headers -H "If-None-Match: \"$ETag\"" http://${SERVER}/${SOURCE} 2> ${TMDIR}/${SOURCE}.error > ${TMDIR}/${SOURCE}

if [ $? -eq 0 ] ; then # Récupération ETag distant réussie

	[ -f ${TMDIR}/${SOURCE}.error ] && rm ${TMDIR}/${SOURCE}.error

        { echo -n "http://${SERVER}/${SOURCE}: " ; grep "^HTTP/" ${TMDIR}/${SOURCE}.headers |tr -d "\r" ; } |logger -t "file-sync"

        # Extraction résultat requète
        grep -q "^HTTP.* 200 OK.*" ${TMDIR}/${SOURCE}.headers

        if [ $? -eq 0 ] ; then

                # Vérification transfert
                h_length=$(grep -i "^Content-Length:" ${TMDIR}/${SOURCE}.headers |tr -d "\r" |awk '{print $2}')
                f_length=$(wc -c ${TMDIR}/${SOURCE} |awk '{print $1}')
                h_length=${h_length:-0} ; f_length=${f_length:-0}
                if [ ${h_length} -ne ${f_length} ] ; then # La taille du fichier ne correspond pas à celle indiquée dans l'entête.
                        echo "download error (h_length=${h_length}, f_length=${f_length})" |logger -t "file-sync"
                        rmdir ${TMDIR}/lock
                        exit 2 # Erreur téléchargement, source pas mise à jour
                fi

                mv ${TMDIR}/${SOURCE} ${DLDIR}/${SOURCE}
                exit 0 # Source mise à jour

        else

                rm ${TMDIR}/${SOURCE}
                exit 1 # Source pas mise à jour

        fi

fi

if [ -f ${TMDIR}/${SOURCE}.error ] ; then
	cat ${TMDIR}/${SOURCE}.error |logger -t "file-sync"
	rm ${TMDIR}/${SOURCE}.error
fi

exit 2 # Erreur téléchargement, source pas mise à jour

#-------------------------------------------------------------------------------
