#!/bin/bash

# A very simple script for checking LACP bonding on GNU/Linux:
# - check all bonding interfaces
# - detect down link
# - detect etherchannel misconfiguration on switch side

# INSTALL:
#
# - Put this script on client side, for example:
#    /usr/local/bin/nrpe_check_lacp
#
# - Add command on client side: (/etc/nagios/nrpe_local.cfg)
#    command[check_lacp]=sudo /usr/local/sbin/nrpe_check_lacp
#
# - Give root rights on client side: (/etc/sudoers)
#    nagios ALL=NOPASSWD:    /usr/local/sbin/nrpe_check_lacp

########################################################################

echo -n "BONDING "

for bond in $(ls /proc/net/bonding) ; do

	# Nombre d'interfaces agrégées
	nop=$(cat /proc/net/bonding/${bond} |grep -c "MII Status: ")

	# Vérifications interfaces "UP"
	msu=$(cat /proc/net/bonding/${bond} |grep -c "MII Status: up")
	if [ ${msu} -ne ${nop} ] ; then
		echo "WARNING:down link on ${bond}"
		exit 1
	fi



	# Vérification interfaces "churned" => pb config côté switch
	(( nop-- ))
	acs=$(cat /proc/net/bonding/${bond} |grep -c "Actor Churn State: none")
	if [ ${acs} -ne ${nop} ] ; then
		echo "WARNING:churned link on ${bond}"
		exit 1
	fi
	

done

echo "OK"
exit 0
