#!/bin/bash

echo -n "BONDING "

for bond in $(ls /proc/net/bonding 2>/dev/null) ; do

	# Nombre d'interfaces agrégées
	nop=$(cat /proc/net/bonding/${bond} |grep -c "MII Status: ")

	# Vérifications interfaces "UP"
	msu=$(cat /proc/net/bonding/${bond} |grep -c "MII Status: up")
	if [ ${msu} -ne ${nop} ] ; then
		echo "WARNING:down link on ${bond}"
		exit 1
	fi



	# Vérification interfaces "churned" => pb config côté switch
	(( nop-- ))
	acs=$(cat /proc/net/bonding/${bond} |grep -c "Actor Churn State: none")
	if [ ${acs} -ne ${nop} ] ; then
		echo "WARNING:churned link on ${bond}"
		exit 1
	fi
	

done

echo "OK"
exit 0
