#!/bin/bash

# Extraction récursive de déclaration SPF
# Testé sur Ubuntu 16.04 LTS

################################################

function parse {
local d D
D=$(dig ${1} txt |awk '{print tolower($0)}' |grep "v=spf" |grep "^${1//./\\.}" |sed 's/^.*v=spf. // ; s/"$//')
for d in $(echo "${D}") ; do
	if [[ ${d} =~ include ]] || [[ ${d} =~ redirect ]]; then
		echo ${d}
        	d=${d#*:}
        	d=${d#*=}
        	parse ${d}
        else
		if [[ ${d} =~ mx: ]] ; then
			n=${d#*:}
			echo -n "${d} ("
			echo -n $(dig A ${n} |grep "^${n//./\.}\." |grep "[[:space:]]*IN[[:space:]]*A[[:space:]]*" |awk '{print $5}')
			echo ")"
		else
			echo ${d}
		fi
	fi
done
}

################################################

[ -z "${1}" ] && { echo "Usage: spf-parse <FQDN>" ; exit 1 ; }

echo ${1}
parse ${1}
